<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AuthController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SetController::create' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\SetController::update' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\TaskController::create' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\TaskController::update' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\AuthController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SetController:create' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\SetController:update' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\TaskController:create' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
    'App\\Controller\\TaskController:update' => ['privates', '.service_locator.voSDoEY', 'get_ServiceLocator_VoSDoEYService.php', true],
], [
    'App\\Controller\\AuthController::login' => '?',
    'App\\Controller\\SetController::create' => '?',
    'App\\Controller\\SetController::update' => '?',
    'App\\Controller\\TaskController::create' => '?',
    'App\\Controller\\TaskController::update' => '?',
    'App\\Controller\\AuthController:login' => '?',
    'App\\Controller\\SetController:create' => '?',
    'App\\Controller\\SetController:update' => '?',
    'App\\Controller\\TaskController:create' => '?',
    'App\\Controller\\TaskController:update' => '?',
]));
